### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/webfont-kit-generator#1]
Current icon is temporal.

**Comment by rafaelmardojai** [comment]
Hmm, I like it but I'm not convinced of the box looking too much like a present. Maybe it could look more like a package?

I hope that don't make it look like some font packages manager.

**Comment by bertob** [comment]
Here's another completely different metaphor suggested by someone on Mastodon:

![image](https://user-images.githubusercontent.com/1908896/136671001-00069a5e-7442-4b63-8e68-dd21fbc099c1.png)

In terms of metaphor I like it, but as an actual icon I'm not sure it's better than the others, it's a bit boring visually (That said, maybe visually boring makes sense for an app that converts font files :D).

**Comment by rafaelmardojai** [comment]
> Here's another completely different metaphor suggested by someone on Mastodon:

Yeah, I also like it, and this metaphor explains better what the app does, although the ultra-generic name will clear any doubt. Also agree that it's a bit boring, but yeah, the app itself is boring :P

Now I'm in a dilemma, I really like the aid kit or present box in the sense of singularity, but this one represents better the app functionality. Maybe is better for this kind of apps to don't have a singular app identity? I don't know.

So I will pick the easy path and trust you on whatever you think works better :P
