### ISSUE TITLE
0.4 not available in Flathub

### ISSUE THREAD

**Issue by zzzazzz** [rafaelmardojai/webfont-kit-generator#24]
Hi, and thanks for this app. Do you know how or when the 0.4 will be available in flathub ? Flat repos are not updated automatically from github repos ?

**Comment by rafaelmardojai** [comment]
Actually it was updated with this PR: https://github.com/flathub/com.rafaelmardojai.WebfontKitGenerator/pull/3. So probably a Flathub issue.

**Comment by rafaelmardojai** [comment]
New version `0.5.0` is published now on flathub.

**Comment by zzzazzz** [comment]
Thks, great !
