### ISSUE TITLE
Broken symbolic icon

### ISSUE THREAD

**Issue by bertob** [rafaelmardojai/webfont-kit-generator#34]
Seems like the symbolic isn't configured correctly, it's not showing up in the shell:

![image](https://user-images.githubusercontent.com/1908896/175746192-6e7a7b9b-ccdf-4396-adfa-a5d4476ba41f.png)

**Comment by rafaelmardojai** [comment]
Yeah, I totally forgot to actually install the icon with meson when it was added.

This is already fixed in master, I'm just waiting for some free time to publish a new minor version of my apps :p
