### ISSUE TITLE
Unable to export Webfont --> Cannot select specific folder

### ISSUE THREAD

**Issue by the-unknown** [rafaelmardojai/webfont-kit-generator#5]
Hey,

I am unable to select a specific folder to export the webfonts to. 
I select my home directory but it's completely empty. I am even unable to create a new folder. 

See screenshot:
https://imgur.com/a/cWOWuAJ

Upon "export" the app seems to generate the fonts, but they cannot be found anywhere.

BTW: I installed the version available to flathub and I am running Linux Mint 20.1

**Comment by rafaelmardojai** [comment]
The app currently uses [GtkFileChooserNative](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html). The issue is probably related to it.
